"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-06-12 19:11:44.617375
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "depositor_positions",
        sa.Column("address", sa.String(length=70), nullable=False),
        sa.Column("principal", sa.BigInteger(), nullable=False),
        sa.Column("join_epoch", sa.Integer(), nullable=True),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("address", name=op.f("pk_depositor_positions")),
    )
    op.create_table(
        "deposits",
        sa.Column("depositor", sa.String(length=70), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=64), nullable=False),
        sa.Column("lt", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.BigInteger(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deposits")),
        sa.UniqueConstraint("tx_hash", name=op.f("uq_deposits_tx_hash")),
    )
    with op.batch_alter_table("deposits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deposits_depositor"), ["depositor"], unique=False)
        batch_op.create_index(batch_op.f("ix_deposits_tx_hash"), ["tx_hash"], unique=False)

    op.create_table(
        "draws",
        sa.Column("epoch", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("seed", sa.String(length=66), nullable=True),
        sa.Column("distributable", sa.BigInteger(), nullable=False),
        sa.Column("skim", sa.BigInteger(), nullable=False),
        sa.Column("num_winners", sa.Integer(), nullable=False),
        sa.Column("settled_ts", sa.BigInteger(), nullable=True),
        sa.Column("settle_tx", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("epoch", name=op.f("pk_draws")),
    )
    op.create_table(
        "epochs",
        sa.Column("epoch", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("started_at", sa.BigInteger(), nullable=True),
        sa.Column("deposit_deadline", sa.BigInteger(), nullable=True),
        sa.Column("harvested_yield", sa.BigInteger(), nullable=False),
        sa.Column("prize_pot", sa.BigInteger(), nullable=False),
        sa.Column("settled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("epoch", name=op.f("pk_epochs")),
    )
    op.create_table(
        "harvests",
        sa.Column("gross_yield", sa.BigInteger(), nullable=False),
        sa.Column("net_yield", sa.BigInteger(), nullable=False),
        sa.Column("lp_burned", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=64), nullable=False),
        sa.Column("lt", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.BigInteger(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_harvests")),
        sa.UniqueConstraint("tx_hash", name=op.f("uq_harvests_tx_hash")),
    )
    with op.batch_alter_table("harvests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_harvests_tx_hash"), ["tx_hash"], unique=False)

    op.create_table(
        "indexer_cursors",
        sa.Column("account", sa.String(length=70), nullable=False),
        sa.Column("last_lt", sa.BigInteger(), nullable=False),
        sa.Column("last_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account", name=op.f("pk_indexer_cursors")),
    )
    op.create_table(
        "payouts",
        sa.Column("winner", sa.String(length=70), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=64), nullable=False),
        sa.Column("lt", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.BigInteger(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payouts")),
        sa.UniqueConstraint("tx_hash", "winner", name=op.f("uq_payouts_tx_hash")),
    )
    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payouts_tx_hash"), ["tx_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_payouts_winner"), ["winner"], unique=False)

    op.create_table(
        "pool_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("deposit_deadline", sa.BigInteger(), nullable=False),
        sa.Column("total_principal", sa.BigInteger(), nullable=False),
        sa.Column("prize_pot", sa.BigInteger(), nullable=False),
        sa.Column("adapter_principal", sa.BigInteger(), nullable=False),
        sa.Column("adapter_lp_balance", sa.BigInteger(), nullable=False),
        sa.Column("stonfi_reserve", sa.BigInteger(), nullable=False),
        sa.Column("stonfi_lp_supply", sa.BigInteger(), nullable=False),
        sa.Column("accrued_yield", sa.BigInteger(), nullable=False),
        sa.Column("masterchain_seqno", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_snapshots")),
    )
    op.create_table(
        "withdrawals",
        sa.Column("depositor", sa.String(length=70), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=64), nullable=False),
        sa.Column("lt", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.BigInteger(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_withdrawals")),
        sa.UniqueConstraint("tx_hash", name=op.f("uq_withdrawals_tx_hash")),
    )
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_withdrawals_depositor"), ["depositor"], unique=False)
        batch_op.create_index(batch_op.f("ix_withdrawals_tx_hash"), ["tx_hash"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_withdrawals_tx_hash"))
        batch_op.drop_index(batch_op.f("ix_withdrawals_depositor"))

    op.drop_table("withdrawals")
    op.drop_table("pool_snapshots")
    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payouts_winner"))
        batch_op.drop_index(batch_op.f("ix_payouts_tx_hash"))

    op.drop_table("payouts")
    op.drop_table("indexer_cursors")
    with op.batch_alter_table("harvests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_harvests_tx_hash"))

    op.drop_table("harvests")
    op.drop_table("epochs")
    op.drop_table("draws")
    with op.batch_alter_table("deposits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deposits_tx_hash"))
        batch_op.drop_index(batch_op.f("ix_deposits_depositor"))

    op.drop_table("deposits")
    op.drop_table("depositor_positions")
    # ### end Alembic commands ###
